### ISSUE TITLE
trying to save: Not an object

### ISSUE THREAD

**Issue by jeffmarshall** [marcello3d/node-mongolian#45]
Everything goes well, I'm able to connect:

```
> var Mongolian = require('mongolian')
> var server = new Mongolian('example.com')
> [debug] mongo://example.com:27017: Connected
[debug] mongo://example.com:27017: Initialized as primary
[info] mongo://example.com:27017: Connected to primary
[debug] Finished scanning... primary? mongo://example.com:27017

> var db = server.db('wiki')
> var articles = db.collection('articles')
```

but then:

```
> articles.insert({attr2: 'yo!'})
Error: Not a valid object
at Function.serializeWithBufferAndIndex       (/Users/jeff/Projects/wiki/node_modules/mongolian/node_modules/mongodb/lib/mongodb/bson/bson.js:652:11)
at [object Object].toBinary (/Users/jeff/Projects/wiki/node_modules/mongolian/node_modules/mongodb/lib/mongodb/commands/insert_command.js:98:55)
at [object Object].send (/Users/jeff/Projects/wiki/node_modules/mongolian/node_modules/mongodb/lib/mongodb/connection.js:251:32)
at /Users/jeff/Projects/wiki/node_modules/mongolian/lib/server.js:260:20
at /Users/jeff/Projects/wiki/node_modules/mongolian/lib/util.js:19:18
at MongolianServer.cacher [as _connection] (/Users/jeff/Projects/wiki/node_modules/mongolian/node_modules/taxman/taxman.js:8:13)
at MongolianServer.sendCommand (/Users/jeff/Projects/wiki/node_modules/mongolian/lib/server.js:254:10)
at /Users/jeff/Projects/wiki/node_modules/mongolian/lib/server.js:148:17
at /Users/jeff/Projects/wiki/node_modules/mongolian/lib/util.js:19:18
at [object Object]._getPrimary (/Users/jeff/Projects/wiki/node_modules/mongolian/lib/server.js:115:35)
```

**Comment by marcello3d** [comment]
This looks like it might be a bug in mongodb-native (or incompatibility) what version of mongodb-native do you have installed? Running `npm ls` in the folder should tell you.

**Comment by marcello3d** [comment]
Is this still an issue?
