### ISSUE TITLE
can't create server instance with mongodb@0.9.7-0

### ISSUE THREAD

**Issue by outsideris** [marcello3d/node-mongolian#60]
├─┬ mongolian@0.1.12 
│ ├── mongodb@0.9.7-0 
│ ├── nodeunit@0.5.3  extraneous
│ ├── taxman@0.1.1 
│ └── waiter@0.1.1 

in this case, when I useing new Mongolian, It occur undefined error. I think because monogb module version.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: undefined is not a function
    at /Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/server.js:211:26
    at MongolianServer.cacher [as _connection](/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/node_modules/taxman/taxman.js:13:13)
    at MongolianServer.sendCommand (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/server.js:248:10)
    at [object Object].<anonymous> (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/server.js:51:20)
    at [object Object].sendCommand (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/db.js:79:21)
    at [object Object].nextBatch (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/cursor.js:135:17)
    at [object Object].next (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/cursor.js:162:14)
    at [object Object].findOne (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/collection.js:53:42)
    at [object Object].runCommand (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/db.js:63:29)
    at scanServer (/Users/outsider/projects/nodejs/nodebook-examples/chapter-07/joinin-mongodb/node_modules/mongolian/lib/server.js:53:21)

So, I change dependency module like this:

└─┬ mongolian@0.1.12 
  ├── mongodb@0.9.6-15 
  ├── nodeunit@0.5.3  extraneous
  ├── taxman@0.1.1 
  └── waiter@0.1.1 

It's working.

**Comment by ghost** [comment]
Confirmed this fix.

**Comment by nanek** [comment]
I also ran into same issue, and resolved with same fix. Thanks.

**Comment by marcello3d** [comment]
Thanks for the report, I'm almost done with upgrading the code to be compatible with the new 0.9.7 connection code.

**Comment by ghost** [comment]
this appears to now be resolved in mongolian@0.1.13, no?

**Comment by marcello3d** [comment]
Correct. For some reason github didn't link the commit to this issue and auto-close it.

**Comment by outsideris** [comment]
Thanks~~~ <3
